config/routes.rb
Rails.application.routes.draw do
  authenticated :user, -> user { user.admin? }  do
    mount DelayedJobWeb, at: "/delayed_job"
  end
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:      'users/registrations'
  }

  namespace :admin do
    resources :users, param: :uuid
    resources :groups, param: :uuid
    resources :idols, param: :uuid

    root 'dashboard#index'
  end

  root 'home#index'
end

app/views/admin/components/_header.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Admin - Jinsoul Ouais', admin_root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbar-content"
            aria-controls="navbar-content"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar-content">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Users', admin_users_path, class: 'nav-link' if can? :read, User %>
        </li>
        <li class="nav-item">
          <%= link_to 'Groups', admin_groups_path, class: 'nav-link' if can? :read, Group %>
        </li>
        <li class="nav-item">
          <%= link_to 'Idols', admin_idols_path, class: 'nav-link' if can? :read, Idol %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a  class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
            Connected as <%= current_user %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Back to site', root_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item' %>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>