config/routes.rb
Rails.application.routes.draw do
  authenticated :user, -> user { user.admin? }  do
    mount DelayedJobWeb, at: "/delayed_job"
  end
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:      'users/registrations'
  }

  namespace :admin do
    resources :users, param: :uuid
    resources :groups, param: :uuid
    resources :idols, param: :uuid

    root 'dashboard#index'
  end

  root 'home#index'
end

app/models/group.rb
class Group < ApplicationRecord
  include WithUuid

  has_many :idols

  validates :name, presence: true

  scope :ordered, -> { order(:name) }

  def to_s
    name
  end
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::ApplicationController
  load_and_authorize_resource find_by: :uuid, id_param: :uuid

  def index
    @groups = @groups.ordered.page(params[:page])
  end

  def show
    @idols = @group.idols.ordered
  end

  def new
  end

  def edit
  end

  def create
    if @group.save
      redirect_to [:admin, @group], notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to [:admin, @group], notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to admin_groups_path, notice: 'Group was successfully destroyed.'
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end
end

app/views/admin/groups/_form.html.erb
<%= simple_form_for [:admin, group] do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :name %>
    </div>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/admin/groups/edit.html.erb
<%= content_for :title, @group %>

<div class="container">
  <h1><%= @group %></h1>

  <%= render 'form', group: @group %>
</div>

app/views/admin/groups/index.html.erb
<%= content_for :title, 'Groups' %>

<div class="container">
  <h1>Groups (<%= @groups.total_count %>)</h1>

  <div class="actions mb-3">
    <%= link_to 'New Group', new_admin_group_path, class: 'btn btn-success' %>
  </div>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td><%= link_to group, [:admin, group] %></td>
          <td>
            <%= link_to 'Edit', [:edit, :admin, group], class: 'btn btn-sm btn-primary' %>
            <%= link_to 'Destroy',
                        [:admin, group],
                        method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class: 'btn btn-sm btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @groups, theme: 'twitter-bootstrap-4' %>
</div>

app/views/admin/groups/new.html.erb
<%= content_for :title, 'New Group' %>

<div class="container">
  <h1>New Group</h1>

  <%= render 'form', group: @group %>
</div>

app/views/admin/groups/show.html.erb
<%= content_for :title, @group %>

<div class="container">
  <h1><%= @group %></h1>

  <div class="actions">
    <%= link_to 'Edit', [:edit, :admin, @group], class: 'btn btn-primary' %>
    <%= link_to 'Destroy',
                [:admin, @group],
                method: :delete,
                data: { confirm: 'Are you sure?' },
                class: 'btn btn-danger' %>
  </div>
</div>