config/routes.rb
Rails.application.routes.draw do
  authenticated :user, -> user { user.admin? }  do
    mount DelayedJobWeb, at: "/delayed_job"
  end
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:      'users/registrations'
  }

  namespace :admin do
    resources :users, param: :uuid
    resources :groups, param: :uuid
    resources :idols, param: :uuid

    root 'dashboard#index'
  end

  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:discord]

  include WithUuid

  enum role: { visitor: 0, admin: 50 }

  validates_presence_of :email
  validates_uniqueness_of :email, allow_blank: true, if: :will_save_change_to_email?
  validates_format_of :email, with: Devise::email_regexp, allow_blank: true, if: :will_save_change_to_email?
  validates_presence_of :password, if: :password_required?
  validates_confirmation_of :password, if: :password_required?
  validate :password_complexity

  def self.from_omniauth(auth)
    user = where(email: auth.info.email).first_or_initialize do |user|
      user.password = "#{Devise.friendly_token[0, 20]}!"
    end
    user.discord_uid = auth.uid
    user.from_discord = true
    user.save
    user
  end

  def to_s
    email
  end

  protected

  def password_required?
    !persisted? || !password.nil? || !password_confirmation.nil?
  end

  def password_complexity
    # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
    return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!,@$%^&*\-+£µ]).{8,70}$/
    errors.add :password, 'complexity requirement not met. Length should be 8-70 characters and include: 1 uppercase, 1 lowercase, 1 digit and 1 special character'
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  load_and_authorize_resource find_by: :uuid, id_param: :uuid

  def index
    @users = @users.page(params[:page])
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if @user.save
      redirect_to [:admin, @user], notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    manage_password
    if @user.update(user_params)
      redirect_to [:admin, @user], notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: 'User was successfully destroyed.'
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name, :last_name, :email, :password,
      :role, :blog_role, :video_role
    )
  end

  def manage_password
    params[:user][:password] ||= ''

    if params[:user][:password].blank?
      params[:user].delete(:password)
    else
      @user.reset_password(params[:user][:password], params[:user][:password])
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :discord

  def discord
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Discord") if is_navigational_format?
    else
      session["devise.discord_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_account_update_params, only: [:update]

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:discord_uid]) unless resource.from_discord?
  end
end

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, user] do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :email %>
      <%= f.input :password,
                  required: user.new_record?,
                  hint: 'Leave blank if you do not wish to change the password' %>
    </div>
    <div class="col-md-6">
      <%= f.input :discord_uid, label: 'Discord ID' %>
      <%= f.input :role, include_blank: false %>
    </div>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/admin/users/edit.html.erb
<%= content_for :title, @user %>

<div class="container">
  <h1><%= @user %></h1>

  <%= render 'form', user: @user %>
</div>

app/views/admin/users/index.html.erb
<%= content_for :title, 'Users' %>

<div class="container">
  <h1>Users (<%= @users.total_count %>)</h1>

  <div class="actions mb-3">
    <%= link_to 'New User', new_admin_user_path, class: 'btn btn-success' %>
  </div>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Email</th>
        <th>Role</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.email, [:admin, user] %></td>
          <td>
            <% if user.admin? %>
              <span class="badge badge-primary">Admin</span>
            <% else %>
              <span class="badge badge-dark">Visitor</span>
            <% end %>
          </td>
          <td>
            <%= link_to 'Edit', [:edit, :admin, user], class: 'btn btn-sm btn-primary' %>
            <%= link_to 'Destroy',
                        [:admin, user],
                        method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class: 'btn btn-sm btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @users, theme: 'twitter-bootstrap-4' %>
</div>

app/views/admin/users/new.html.erb
<%= content_for :title, 'New User' %>

<div class="container">
  <h1>New User</h1>

  <%= render 'form', user: @user %>
</div>

app/views/admin/users/show.html.erb
<%= content_for :title, @user %>

<div class="container">
  <h1><%= @user %></h1>

  <p><strong>Email:</strong> <%= @user.email %></p>
  <p><strong>Discord ID:</strong> <%= @user.discord_uid %></p>
  <p><strong>Role:</strong> <%= @user.role.humanize %></p>
  <p><strong>Logged via Discord:</strong> <%= @user.from_discord? %></p>

  <div class="actions">
    <%= link_to 'Edit', [:edit, :admin, @user], class: 'btn btn-primary' %>
    <%= link_to 'Destroy',
                [:admin, @user],
                method: :delete,
                data: { confirm: 'Are you sure?' },
                class: 'btn btn-danger' %>
  </div>
</div>