config/routes.rb
Rails.application.routes.draw do
  authenticated :user, -> user { user.admin? }  do
    mount DelayedJobWeb, at: "/delayed_job"
  end
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:      'users/registrations'
  }

  namespace :admin do
    resources :users, param: :uuid
    resources :groups, param: :uuid
    resources :idols, param: :uuid

    root 'dashboard#index'
  end

  root 'home#index'
end

app/models/idol.rb
class Idol < ApplicationRecord
  include WithUuid

  belongs_to :group

  validates :name, :group_id, presence: true

  scope :ordered, -> { order(:name) }

  def to_s
    "#{group} #{name}"
  end
end

app/controllers/admin/idols_controller.rb
class Admin::IdolsController < Admin::ApplicationController
  load_and_authorize_resource find_by: :uuid, id_param: :uuid

  def index
    @idols = @idols.includes(:group).ordered.page(params[:page])
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if @idol.save
      redirect_to [:admin, @idol], notice: 'Idol was successfully created.'
    else
      render :new
    end
  end

  def update
    if @idol.update(idol_params)
      redirect_to [:admin, @idol], notice: 'Idol was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @idol.destroy
    redirect_to admin_idols_path, notice: 'Idol was successfully destroyed.'
  end

  private

  def idol_params
    params.require(:idol).permit(:name, :group_id)
  end
end

app/views/admin/idols/_form.html.erb
<%= simple_form_for [:admin, idol] do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :name %>
      <%= f.association :group,
                        collection: Group.all.ordered,
                        include_blank: 'Select a group' %>
    </div>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/admin/idols/edit.html.erb
<%= content_for :title, @idol %>

<div class="container">
  <h1><%= @idol %></h1>

  <%= render 'form', idol: @idol %>
</div>

app/views/admin/idols/index.html.erb
<%= content_for :title, 'Idols' %>

<div class="container">
  <h1>Idols (<%= @idols.total_count %>)</h1>

  <div class="actions mb-3">
    <%= link_to 'New Idol', new_admin_idol_path, class: 'btn btn-success' %>
  </div>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Group</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @idols.each do |idol| %>
        <tr>
          <td><%= link_to idol.name, [:admin, idol] %></td>
          <td><%= link_to idol.group, [:admin, idol.group] %></td>
          <td>
            <%= link_to 'Edit', [:edit, :admin, idol], class: 'btn btn-sm btn-primary' %>
            <%= link_to 'Destroy',
                        [:admin, idol],
                        method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class: 'btn btn-sm btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @idols, theme: 'twitter-bootstrap-4' %>
</div>

app/views/admin/idols/new.html.erb
<%= content_for :title, 'New Idol' %>

<div class="container">
  <h1>New Idol</h1>

  <%= render 'form', idol: @idol %>
</div>

app/views/admin/idols/show.html.erb
<%= content_for :title, @idol %>

<div class="container">
  <h1><%= @idol %></h1>

  <p><strong>Group:</strong> <%= link_to @idol.group, [:admin, @idol.group] %></p>

  <div class="actions">
    <%= link_to 'Edit', [:edit, :admin, @idol], class: 'btn btn-primary' %>
    <%= link_to 'Destroy',
                [:admin, @idol],
                method: :delete,
                data: { confirm: 'Are you sure?' },
                class: 'btn btn-danger' %>
  </div>
</div>